sudo: required
services:
   - docker

before_install:
   - docker build -t sdiokhe/docker-react -f Dockerfile.dev .

script:
   - docker run -e CI=true sdiokhe/docker-react npm run test

deploy:
   provider: elasticbeanstalk
   region: "us-east-1" 
   app: "docker"
   env: "Docker-env"
   bucket_name: "elasticbeanstalk-us-east-1-939132397821"
   bucket_path: "docker"
   on:
     branch: master
   access_key_id: 
     secure: $AWS_ACCESS_KEY
   secret_access_key:
     secure: "$AWS_SECRET_KEY"
